begin_unit
comment|'# See http://code.google.com/p/python-nose/issues/detail?id=373'
nl|'\n'
comment|'# The code below enables nosetests to work with i18n _() blocks'
nl|'\n'
nl|'\n'
name|'import'
name|'__builtin__'
newline|'\n'
nl|'\n'
name|'setattr'
op|'('
name|'__builtin__'
op|','
string|"'_'"
op|','
name|'lambda'
name|'x'
op|':'
name|'x'
op|')'
newline|'\n'
nl|'\n'
endmarker|''
end_unit
