begin_unit
comment|'#!/usr/bin/python'
nl|'\n'
comment|'# Copyright (c) 2010 OpenStack, LLC.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Licensed under the Apache License, Version 2.0 (the "License");'
nl|'\n'
comment|'# you may not use this file except in compliance with the License.'
nl|'\n'
comment|'# You may obtain a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS,'
nl|'\n'
comment|'# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or'
nl|'\n'
comment|'# implied.'
nl|'\n'
comment|'# See the License for the specific language governing permissions and'
nl|'\n'
comment|'# limitations under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'setuptools'
name|'import'
name|'setup'
op|','
name|'find_packages'
newline|'\n'
nl|'\n'
DECL|variable|name
name|'name'
op|'='
string|"'swift'"
newline|'\n'
DECL|variable|version
name|'version'
op|'='
string|"'1.0.0'"
newline|'\n'
nl|'\n'
name|'setup'
op|'('
nl|'\n'
DECL|variable|name
name|'name'
op|'='
name|'name'
op|','
nl|'\n'
DECL|variable|version
name|'version'
op|'='
name|'version'
op|','
nl|'\n'
DECL|variable|description
name|'description'
op|'='
string|"'Swift'"
op|','
nl|'\n'
DECL|variable|license
name|'license'
op|'='
string|"'Apache License (2.0)'"
op|','
nl|'\n'
DECL|variable|author
name|'author'
op|'='
string|"'OpenStack, LLC.'"
op|','
nl|'\n'
DECL|variable|url
name|'url'
op|'='
string|"'https://launchpad.net/swift'"
op|','
nl|'\n'
DECL|variable|packages
name|'packages'
op|'='
name|'find_packages'
op|'('
name|'exclude'
op|'='
op|'['
string|"'test'"
op|','
string|"'bin'"
op|']'
op|')'
op|','
nl|'\n'
DECL|variable|test_suite
name|'test_suite'
op|'='
string|"'nose.collector'"
op|','
nl|'\n'
DECL|variable|classifiers
name|'classifiers'
op|'='
op|'['
nl|'\n'
string|"'Development Status :: 4 - Beta'"
op|','
nl|'\n'
string|"'License :: OSI Approved :: Apache Software License'"
op|','
nl|'\n'
string|"'Operating System :: POSIX :: Linux'"
op|','
nl|'\n'
string|"'Programming Language :: Python :: 2.6'"
op|','
nl|'\n'
string|"'Environment :: No Input/Output (Daemon)'"
op|','
nl|'\n'
op|']'
op|','
nl|'\n'
DECL|variable|scripts
name|'scripts'
op|'='
op|'['
string|"'bin/st'"
op|','
string|"'bin/swift-account-auditor'"
op|','
nl|'\n'
string|"'bin/swift-account-audit'"
op|','
string|"'bin/swift-account-reaper'"
op|','
nl|'\n'
string|"'bin/swift-account-replicator'"
op|','
string|"'bin/swift-account-server'"
op|','
nl|'\n'
string|"'bin/swift-auth-create-account'"
op|','
nl|'\n'
string|"'bin/swift-auth-recreate-accounts'"
op|','
string|"'bin/swift-auth-server'"
op|','
nl|'\n'
string|"'bin/swift-container-auditor'"
op|','
nl|'\n'
string|"'bin/swift-container-replicator'"
op|','
nl|'\n'
string|"'bin/swift-container-server'"
op|','
string|"'bin/swift-container-updater'"
op|','
nl|'\n'
string|"'bin/swift-drive-audit'"
op|','
string|"'bin/swift-get-nodes'"
op|','
nl|'\n'
string|"'bin/swift-init'"
op|','
string|"'bin/swift-object-auditor'"
op|','
nl|'\n'
string|"'bin/swift-object-info'"
op|','
nl|'\n'
string|"'bin/swift-object-replicator'"
op|','
nl|'\n'
string|"'bin/swift-object-server'"
op|','
nl|'\n'
string|"'bin/swift-object-updater'"
op|','
string|"'bin/swift-proxy-server'"
op|','
nl|'\n'
string|"'bin/swift-ring-builder'"
op|','
string|"'bin/swift-stats-populate'"
op|','
nl|'\n'
string|"'bin/swift-stats-report'"
op|']'
nl|'\n'
op|')'
newline|'\n'
endmarker|''
end_unit
