begin_unit
comment|'# Copyright (c) 2014 OpenStack Foundation'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Licensed under the Apache License, Version 2.0 (the "License");'
nl|'\n'
comment|'# you may not use this file except in compliance with the License.'
nl|'\n'
comment|'# You may obtain a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS,'
nl|'\n'
comment|'# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or'
nl|'\n'
comment|'# implied.'
nl|'\n'
comment|'# See the License for the specific language governing permissions and'
nl|'\n'
comment|'# limitations under the License.'
nl|'\n'
nl|'\n'
name|'import'
name|'locale'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|config
name|'config'
op|'='
op|'{'
op|'}'
newline|'\n'
DECL|variable|orig_collate
name|'orig_collate'
op|'='
string|"''"
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|setup_package
name|'def'
name|'setup_package'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'global'
name|'orig_collate'
newline|'\n'
name|'orig_collate'
op|'='
name|'locale'
op|'.'
name|'setlocale'
op|'('
name|'locale'
op|'.'
name|'LC_COLLATE'
op|')'
newline|'\n'
name|'global'
name|'config'
newline|'\n'
name|'locale'
op|'.'
name|'setlocale'
op|'('
name|'locale'
op|'.'
name|'LC_COLLATE'
op|','
name|'config'
op|'.'
name|'get'
op|'('
string|"'collate'"
op|','
string|"'C'"
op|')'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|teardown_package
dedent|''
name|'def'
name|'teardown_package'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'global'
name|'orig_collate'
newline|'\n'
name|'locale'
op|'.'
name|'setlocale'
op|'('
name|'locale'
op|'.'
name|'LC_COLLATE'
op|','
name|'orig_collate'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
