begin_unit
comment|'# Copyright (c) 2010-2012 OpenStack, LLC.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Licensed under the Apache License, Version 2.0 (the "License");'
nl|'\n'
comment|'# you may not use this file except in compliance with the License.'
nl|'\n'
comment|'# You may obtain a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS,'
nl|'\n'
comment|'# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or'
nl|'\n'
comment|'# implied.'
nl|'\n'
comment|'# See the License for the specific language governing permissions and'
nl|'\n'
comment|'# limitations under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'swift'
op|'.'
name|'container'
name|'import'
name|'server'
name|'as'
name|'container_server'
newline|'\n'
name|'from'
name|'swift'
op|'.'
name|'common'
name|'import'
name|'db'
op|','
name|'db_replicator'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ContainerReplicator
name|'class'
name|'ContainerReplicator'
op|'('
name|'db_replicator'
op|'.'
name|'Replicator'
op|')'
op|':'
newline|'\n'
DECL|variable|server_type
indent|'    '
name|'server_type'
op|'='
string|"'container'"
newline|'\n'
DECL|variable|brokerclass
name|'brokerclass'
op|'='
name|'db'
op|'.'
name|'ContainerBroker'
newline|'\n'
DECL|variable|datadir
name|'datadir'
op|'='
name|'container_server'
op|'.'
name|'DATADIR'
newline|'\n'
DECL|variable|default_port
name|'default_port'
op|'='
number|'6001'
newline|'\n'
nl|'\n'
DECL|member|report_up_to_date
name|'def'
name|'report_up_to_date'
op|'('
name|'self'
op|','
name|'full_info'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'for'
name|'key'
name|'in'
op|'('
string|"'put_timestamp'"
op|','
string|"'delete_timestamp'"
op|','
string|"'object_count'"
op|','
nl|'\n'
string|"'bytes_used'"
op|')'
op|':'
newline|'\n'
indent|'            '
name|'if'
name|'full_info'
op|'['
string|"'reported_'"
op|'+'
name|'key'
op|']'
op|'!='
name|'full_info'
op|'['
name|'key'
op|']'
op|':'
newline|'\n'
indent|'                '
name|'return'
name|'False'
newline|'\n'
dedent|''
dedent|''
name|'return'
name|'True'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
