begin_unit
comment|'# Copyright (c) 2013 Hewlett-Packard Development Company, L.P.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Licensed under the Apache License, Version 2.0 (the "License");'
nl|'\n'
comment|'# you may not use this file except in compliance with the License.'
nl|'\n'
comment|'# You may obtain a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS,'
nl|'\n'
comment|'# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or'
nl|'\n'
comment|'# implied.'
nl|'\n'
comment|'# See the License for the specific language governing permissions and'
nl|'\n'
comment|'# limitations under the License.'
nl|'\n'
nl|'\n'
name|'import'
name|'os'
newline|'\n'
name|'import'
name|'gettext'
newline|'\n'
nl|'\n'
name|'import'
name|'pkg_resources'
newline|'\n'
nl|'\n'
name|'try'
op|':'
newline|'\n'
comment|"# First, try to get our version out of PKG-INFO. If we're installed,"
nl|'\n'
comment|"# this'll let us find our version without pulling in pbr. After all, if"
nl|'\n'
comment|"# we're installed on a system, we're not in a Git-managed source tree, so"
nl|'\n'
comment|"# pbr doesn't really buy us anything."
nl|'\n'
indent|'    '
name|'__version__'
op|'='
name|'__canonical_version__'
op|'='
name|'pkg_resources'
op|'.'
name|'get_provider'
op|'('
nl|'\n'
name|'pkg_resources'
op|'.'
name|'Requirement'
op|'.'
name|'parse'
op|'('
string|"'swift'"
op|')'
op|')'
op|'.'
name|'version'
newline|'\n'
dedent|''
name|'except'
name|'pkg_resources'
op|'.'
name|'DistributionNotFound'
op|':'
newline|'\n'
comment|"# No PKG-INFO? We're probably running from a checkout, then. Let pbr do"
nl|'\n'
comment|'# its thing to figure out a version number.'
nl|'\n'
indent|'    '
name|'import'
name|'pbr'
op|'.'
name|'version'
newline|'\n'
DECL|variable|_version_info
name|'_version_info'
op|'='
name|'pbr'
op|'.'
name|'version'
op|'.'
name|'VersionInfo'
op|'('
string|"'swift'"
op|')'
newline|'\n'
DECL|variable|__version__
name|'__version__'
op|'='
name|'_version_info'
op|'.'
name|'release_string'
op|'('
op|')'
newline|'\n'
DECL|variable|__canonical_version__
name|'__canonical_version__'
op|'='
name|'_version_info'
op|'.'
name|'version_string'
op|'('
op|')'
newline|'\n'
nl|'\n'
DECL|variable|_localedir
dedent|''
name|'_localedir'
op|'='
name|'os'
op|'.'
name|'environ'
op|'.'
name|'get'
op|'('
string|"'SWIFT_LOCALEDIR'"
op|')'
newline|'\n'
DECL|variable|_t
name|'_t'
op|'='
name|'gettext'
op|'.'
name|'translation'
op|'('
string|"'swift'"
op|','
name|'localedir'
op|'='
name|'_localedir'
op|','
name|'fallback'
op|'='
name|'True'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|gettext_
name|'def'
name|'gettext_'
op|'('
name|'msg'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
name|'_t'
op|'.'
name|'gettext'
op|'('
name|'msg'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
