begin_unit
comment|'# Copyright (c) 2010 OpenStack, LLC.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Licensed under the Apache License, Version 2.0 (the "License");'
nl|'\n'
comment|'# you may not use this file except in compliance with the License.'
nl|'\n'
comment|'# You may obtain a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS,'
nl|'\n'
comment|'# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or'
nl|'\n'
comment|'# implied.'
nl|'\n'
comment|'# See the License for the specific language governing permissions and'
nl|'\n'
comment|'# limitations under the License.'
nl|'\n'
nl|'\n'
string|'""" Tests for swift.common.compressing_file_reader """'
newline|'\n'
nl|'\n'
name|'import'
name|'unittest'
newline|'\n'
name|'import'
name|'cStringIO'
newline|'\n'
nl|'\n'
name|'from'
name|'swift'
op|'.'
name|'common'
op|'.'
name|'compressing_file_reader'
name|'import'
name|'CompressingFileReader'
newline|'\n'
nl|'\n'
DECL|class|TestCompressingFileReader
name|'class'
name|'TestCompressingFileReader'
op|'('
name|'unittest'
op|'.'
name|'TestCase'
op|')'
op|':'
newline|'\n'
nl|'\n'
DECL|member|test_read
indent|'    '
name|'def'
name|'test_read'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'plain'
op|'='
string|"'obj\\ndata'"
newline|'\n'
name|'s'
op|'='
name|'cStringIO'
op|'.'
name|'StringIO'
op|'('
name|'plain'
op|')'
newline|'\n'
name|'expected'
op|'='
string|"'\\x1f\\x8b\\x08\\x00\\x00\\x00\\x00\\x00\\x02\\xff\\xcaO\\xca\\xe2JI,'"
string|"'I\\x04\\x00\\x00\\x00\\xff\\xff\\x03\\x00P(\\xa8\\x1f\\x08\\x00\\x00'"
string|"'\\x00'"
newline|'\n'
name|'x'
op|'='
name|'CompressingFileReader'
op|'('
name|'s'
op|')'
newline|'\n'
name|'compressed'
op|'='
string|"''"
op|'.'
name|'join'
op|'('
name|'iter'
op|'('
name|'lambda'
op|':'
name|'x'
op|'.'
name|'read'
op|'('
op|')'
op|','
string|"''"
op|')'
op|')'
newline|'\n'
name|'self'
op|'.'
name|'assertEquals'
op|'('
name|'compressed'
op|','
name|'expected'
op|')'
newline|'\n'
name|'self'
op|'.'
name|'assertEquals'
op|'('
name|'x'
op|'.'
name|'read'
op|'('
op|')'
op|','
string|"''"
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
